forcedotcom/nodejs-sf-fx-buildpack

buildpack.toml, middleware/index.ts, middleware/package-lock.json, middleware/package.json, middleware/test/unit/ContextTests.ts
TODO:
SDK now has a Secrets api to simplify loading/caching evergreen runtime secrets in SDK >= 1.1.0.  Need to initialize that when Org is initialized.
=> [for DevPreview] Use SDK Context secrets API

buildpack.toml, middleware/package-lock.json, middleware/package.json
- Bump sdk version, pin with `^` to allow using latest compatible version rather than exact
- bump buildpack.toml
=> Switch to salesforce-sdk 1.1.1

bin/build, buildpack.toml, middleware/index.ts, middleware/package-lock.json, middleware/package.json, middleware/tsconfig.json
Changes to reduce the build times for subsequent builds by:
- import optimization
- caching `node_modules`
- caching 'dist'
- excluding `devDependencies` during `npm install`
=> optimize buildpack

bin/build, buildpack.toml, middleware/package-lock.json, middleware/package.json
The builder sets `DEBUG_PORT` when running the `:start` command. We can use that to key off of and automatically emit the `NODE_OPTIONS` with that port so that users can freely debug.
Builder sets the platform env var here: https://github.com/heroku/builder/blob/a160a66cf3510694c45231d93cc7e2a32d25a945/develop/action.go#L270
Reopen of: https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pull/32 (fork meant no circleCI run)
=> feat: create NODE_OPTIONS for debugging when in development mode

bin/build, buildpack.toml, middleware/package-lock.json, middleware/package.json
This fixes a bug in the way we were writing cache metadata for the `dist` cache layer.  We were appending to the file causing the `dist.toml` to become corrupt.  For example:
```
build = false
launch = false
cache = true
[metadata]
package_lock_checksum = "8a7c736358d7f622fa4c037fc8e344ea89d4b4bf1734a67f6011396c98aba84e"
cache = true
build = false
launch = false
[metadata]
package_lock_checksum = "62c6986740a9a15706b93b1c64a6434a7dd663e4b32a985497cc6ba5cc7b647a"
```
=> fix: dist.toml corruption during caching

Makefile, bin/build, buildpack.toml, middleware/package-lock.json, middleware/package.json
This PR aims to improve build performance and slim runtime dependencies for function builds. By compiling JS on buildpack release instead of during builds, we gain these benefits:
- Typescript is not installed. We save the installation costs in both build time and overall image size.
- We're no longer compiling the middleware. We save build time here, and also save time and storage by not caching the compiled artifacts.
=> Precompile JS in buildpack releases

bin/detect, buildpack.toml, middleware/package-lock.json, middleware/package.json
The latest riff update meant we are accidentally skipping the middleware. Fix is to reference the expected middleware as the riff target.
[Example](https://github.com/projectriff/node-function-buildpack/blob/532653d2857e003482d4e9cf890b3e240cc17c9a/node/build_test.go#L57)
Found failure here: https://app.circleci.com/pipelines/github/heroku/evergreen-plugin-build/606/workflows/56140e94-1fe3-4e84-91f2-4c8eae043e8a/jobs/2314/steps
The `FUNCTION_URI` was `/workspace` (default) instead of `/layers/salesforce_nodejs-fn/middleware/dist`
=> fix: update metadata key from fn to artifact

bin/build, buildpack.toml, middleware/index.ts, middleware/package-lock.json, middleware/package.json, middleware/userFnLoader.ts
By `require(userFn)` during the build phase, we can detect invalid `package.json` and invalid `main: "yourfile.js"` values. This does mean we pay the cost of `require` of the user function and its dependencies during build. It also means that code outside of the function may execute during `require`. If, say, a user were to code in database migrations or something dangerous in their `index.js` that code would be attempted during the build's `require` instead of on function pod start. I'm not sure we have any guidelines past what the funciton should look like today.
Here is what an invalid `main` value looks like.
[W-7659608](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008D5iPIAS/view)
=> feat: load user defined function during build

.gitignore, Dockerfile, buildpack.toml, middleware/package-lock.json, middleware/package.json
* latest sf-fx-sdk-nodejs release (https://github.com/forcedotcom/sf-fx-sdk-nodejs/releases/tag/v1.3.0), backward compatible with 1.2.0 and 1.1.x
* bump buildpack.toml version
=> Bump to latest sf-fx-sdk-nodejs version, prepare for release

middleware/index.ts, middleware/lib/sfMiddleware.ts, middleware/test/unit/ContextTests.ts, middleware/test/unit/FunctionTestUtils.ts, middleware/test/unit/InvokeTests.ts
We need to handle both v0.2 and v1.0 of the CloudEvents spec for backwards compatibility:
https://github.com/cloudevents/spec/blob/v0.2/spec.md
https://github.com/cloudevents/spec/blob/v1.0/spec.md
=> Support CloudEvents v1.0 spec, in addition to v0.2

middleware/userFnLoader.ts
Without a `main` key in `package.json`, the loading of the user function fails. This is due to the `main` variable remaining `undefined` and `path.join` failing. By defaulting to empty string, the `path.join` will no longer fail. This will allow folder-level import of the user function.
=> fix: support missing main key in package.json

.gitignore, Dockerfile, Makefile, buildpack.toml, middleware/index.ts, middleware/lib/sfMiddleware.ts, middleware/package-lock.json, middleware/package.json, middleware/test/unit/ContextTests.ts, middleware/test/unit/FunctionTestUtils.ts, middleware/test/unit/InvokeTests.ts, middleware/tsconfig.json, middleware/userFnLoader.ts
Fix crashes in middleware 1.6.0 via
- Using cloudevents-sdk to validate and parse incoming cloudevent in any of its supported HTTP formats
. because evergreen:function:invoke uses HTTP binary 0.3 by default, core 226 uses json structured 0.3, core 228 will use json structure 1.0
TODO:
=> Handle full matrix of CloudEvents formats: 0.3 vs 1.0, structured json vs HTTP binary

bin/build, middleware/index.ts, middleware/userFnLoader.ts
Symlinking the user function as a middleware dependency allows us to use node's native module resolution system and support multiple installations of the same package. This will prevent functions from crashing when using a different version of the `@salesforce/salesforce-sdk` than what is used in this middleware. 
Note that this does not enforce compatibility between of the customer's and middleware's SDK version. This allows each to run it's own version. This could still be confusing, and we should (at a minimum) add warnings when we see mismatches in another PR.
An example directory structure after this change looks like this:
```
heroku@0b9b708b75cb:/workspace$ cat /layers/salesforce_nodejs-fn/middleware/node_modules/\@salesforce/salesforce-sdk/package.json | grep "version"
"version": …
```
=> Install user's function as a node module

bin/build, middleware/test/unit/VersionCheckerTests.ts, middleware/versionChecker.ts
In #50, we're allowing broad incompatiblities between the function and middleware `@salesforce/salesforce-sdk` versions. This is likely to cause confusion and potentially errors as a result. We'd like to at least warn customers when we can detect an incompatibility. This adds that messaging.
Like #50, the work is linked to [this GUS item](https://gus.lightning.force.com/a07B0000008NmGzIAK).
=> Check and warn when user and middleware SDK versions are incompatible

buildpack.toml, middleware/index.ts, middleware/lib/sfMiddleware.ts, middleware/package-lock.json, middleware/package.json, middleware/test/unit/FunctionTestUtils.ts
* Fix for async requests passing through original content-length header (remove and let REST client set new one)
* Upgrade to CloudEvents 3.1.0 SDK and refactor to new API
* Prep for 1.9.0 release
=> Async fix, CloudEvents 3.1.0, prep for 1.9.0 release

buildpack.toml, middleware/index.ts, middleware/package.json
The latest `evergreen-build 0.17.0` plugin will send properly-escaped JSON `string` values on an `sfdx evergreen:function:invoke` call when the payload is not a parseable JSON object.  Unfortunately, the middleware made some prior assumptions about the payload being `object`-only, so was checking for keys without checking if it was an object first.  And, because the riff middleware strips the quotes from the JSON string body (if a string is posted), we need to add those back in before Cloudevents parsing occurs.
== Verification
To verify, create a `payload.txt` file that contains non-JSON content but a couple special json chars that require escaping:
```text
[This
is. "something" }
payload
```
In one window, start your function with current (1.9.0) middleware:
```sh
$ sfdx …
```
=> Fix middleware error "Cannot use 'in' operator to search for 'data' in <string>"

buildpack.toml, middleware/index.ts, middleware/package.json
* headers are lower cased at start of `systemFn`
* header prevents infinite loop, so check for header also needs to be lower cased
* Prep for 1.9.2 release
=> bugfix(middleware): header check for async fulfill requests needs to be lower-case

bin/detect
Now that `function.toml` is required to use the CLI with functions, and that `function.toml` is included in all new functions, we can update `detect` to match. This means we can more authoritatively detect the difference between a Node Salesforce Function and a more generic node app, and even have the nodejs and sf-fx buildpacks in the same builder.
[GUS Item](https://gus.lightning.force.com/a07B0000008UsrfIAC)
=> Require a function.toml to pass detection

bin/build, buildpack.toml, middleware/package.json
Users may see errors like the following when triggering rebuilds during in a `sfdx evergreen:function:start` session:
```
2020-09-02T09:41:38 Salesforce function package name(my-neat-function) conflicts with existing module. Change the 'name' in package.json.
```
This happens because we create the symlink in the first build, and the successive build still has the symlink, so we think it's a user-installed package. This clears the symlink if it exists at the beginning of the build to avoid this problem.
=> Prevent module errors on successive builds in the same container

.vscode/launch.json, buildpack.toml, middleware/index.ts, middleware/lib/FunctionInvocationRequest.ts, middleware/lib/constants.ts, middleware/lib/sfMiddleware.ts, middleware/package-lock.json, middleware/package.json, middleware/test/fixtures/functions/mock/index.js, middleware/test/unit/ContextTests.ts, middleware/test/unit/FunctionTestUtils.ts, middleware/test/unit/InvokeTests.ts
- Error handling:
- Internal errors return `503`
- Function errors return `500`
- Return `x-extra-info` header, URI encoded, as (stack trimmed to last `/middleware/index` frame):
```
ExtraInfo {
requestId: string; // incoming request id
source: string; // incoming ce.source
execTimeMs: number; // function invocation time
stack?: string; // error stack, if applicable
}
```
- Remove async behavior.
- Initialize APIs (`org.data`, `UnitofWork`) even w/o `accessToken`.
- Fix tests
=> Error handling updates; remove async behavior

buildpack.toml, middleware/index.ts, middleware/package-lock.json, middleware/package.json
Part 1 of 2 for [W-8111231](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07B0000008fm5kIAA)
Since RIFF Invoker's HTTP Streaming adapter *only* supports `POST /` requests, this seems like the least-invasive way to add support for health checks from Runtime Infra -> Sidecar -> Function.  This should ensure that the Function container is a) running, b) listening on its $PORT, c) has a functioning RIFF invoker, d) has a functioning Node process capable of receiving function invocations.
PR for sf-fx-proxy to follow.
=> Support an HTTP health check from the sidecar/proxy

buildpack.toml, middleware/package-lock.json, middleware/package.json, middleware/userFnLoader.ts
The throw was not causing a failure anymore.
=> Fixed userfn not erroring out if sdk is too old

bin/build, buildpack.toml, middleware/package.json
This buildpack assumed that builds would always occur in `/workspace`. While this is true in function builds today, as we move toward multiple function architectures, this won't be the case. We might be building in something like `/workspace/function/sms-handler`. This uses `$(pwd)` to figure out the build directory, which matches the [buildpacks spec](https://github.com/buildpacks/spec/blob/main/buildpack.md#build).
=> Dynamic workspace/build directory

bin/detect, buildpack.toml, middleware/package.json
The `..` here would cause issues if the build executed in a directory like `/workspace/myfunction` instead of `/workspace`. It was causing Riff to look for the artifact in `/workspace/layers/salesforce_nodejs-fn/middleware/dist`, which doesn't exist. I've tested this change locally with a custom builder and a newly scaffolded salesforce function and it still ran.
=> Use absolute artifact location

bin/detect, buildpack.toml, middleware/package.json
The change made in #66 didn't work with the Riff invoker as expected. Riff wants to join the `artifact` string to the `pwd` to find the artifact. So in the previous PR, it would attempt to find `/workspace/layers/salesforce_nodejs-fn/middleware/dist`, where we want it to look in `/layers/salesforce_nodejs-fn/middleware/dist` . To solve the issue of building in subdirectories of `/workspace` (the problem we wanted to solve in #66), I'm adding a few more parent directory transitions to make sure we get all the way back to root. This should allow builds of up to two directories deep to compile and run.
=> Artifact needs to be relative
